name: CI Pipeline

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/url_shortener_fe:dev

      - name: Deploy latest image
        uses: fifsky/ssh-action@master
        with:
          command: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/url_shortener_fe:dev
            docker stop url_shortener_fe
            docker rm url_shortener_fe
            docker run -d -p 80:80 --env-file=fe.env --name=url_shortener_be ${{ secrets.DOCKER_USERNAME }}/url_shortener_fe:dev
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY}}
